spring: 
  profiles: 
    active: dev
---
spring: 
  profiles: dev  #开发环境
  application: 
    name: springcloudtest_config_zsc_dev
---
spring: 
  profiles: test  #测试环境
  application: 
    name: springcloudtest_config_zsc_test
    
# 请保存为UTF-8格式