spring: 
  profiles: 
    active: dev
---
server: 
  port: 7001
  
spring: 
  profiles: dev
  application: 
    name: springcloudtest_config_eureka_client

eureka:
  instance:
    hostname: zsc7001.com  #eureka服务端的实例名称
  client:
    register-with-eureka: false  #false标识不向服务中心注册自己
    fetch-registry: false  #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索
    serviceUrl:
      defaultZone:http://zsc7001.com:7001/eureka/
---
server: 
  port: 7001
  
spring: 
  profiles: test
  application: 
    name: springcloudtest_config_eureka_client

eureka: 
  instance: 
    hostname: eureka7001.com
  client: 
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone:http://zsc7001.com:7001/eureka/